### ISSUE TITLE
can alice support EDDSA ?

### ISSUE THREAD

**Issue by lyh168** [getamis/alice#104]
can alice support EDDSA ?

**Comment by cychuang0924** [comment]
This is a good question. I will discuss it with my colleague.

**Comment by cychuang0924** [comment]
Sorry for replying you so late. We have added it in our schedule and also look forward to release it.

**Comment by mechanicals** [comment]
@cychuang0924 : any timelines around this enhancement.

**Comment by cychuang0924** [comment]
@mechanicals Thanks for being there. @markya0616 is organizing our code ref. https://github.com/getamis/alice/pull/137 now.
