### ISSUE TITLE
multi sign/keygen request at same time

### ISSUE THREAD

**Issue by justaskan** [getamis/alice#105]
Is alice can handle 2 key sign/keygen requesed at same time ?

**Comment by cychuang0924** [comment]
Sorry! Could you describe it more clearly, so that I am able to answer it correctly!

**Comment by justaskan** [comment]
Assume that a signature request is sent to Alice. At the same moment when the first request is sent, a different signature request is sent by another user to Alice. Given that for each request a number of messages are exchanged between the nodes, is the designed protocol for Alice to process the separation and process of the messages to both requests? or it will be confused ?

**Comment by markya0616** [comment]
In our design, one Alice only handle one signature request, but the application can have many Alices at the same time. In your cases, your application should add some identifiers or use different connections to distinguish different signature requests and pass them to the correct Alice.
