### ISSUE TITLE
 Can this sign other information？

### ISSUE THREAD

**Issue by zhangtianai** [getamis/alice#108]
```
mySigner, err = signer.NewSigner(signerPeerManager, publicKey, homo, share, bks, msg, listener)
if err != nil {
    // handle error
}
mySigner.Start()
// send out public key message...
mySigner.Stop()
signerResult, err := mySigner.GetResult()
if err != nil {
    // handle error
}
```
Q1: Can the parameter msg be other information？
Q2:Can msg be included in the  signerResult after the signature is successful?
Q3:What did msg do during the signing process？

**Comment by markya0616** [comment]
Q1: Can the parameter msg be other information？
> msg is a byte array, so it can be any information.

Q2:Can msg be included in the signerResult after the signature is successful?
> In our design, the signerResult only includes the generated data. However, if you want it, you can clone our code and modify it.

Q3:What did msg do during the signing process？
> Please check our [Readme](https://github.com/getamis/alice#signer-1). The msg is the message to be signed
