### ISSUE TITLE
can reshare support share private key recover ?

### ISSUE THREAD

**Issue by lyh168** [getamis/alice#115]
for  this scene, if i lose my share private key, how can i  recover the lost share private key。

**Comment by cychuang0924** [comment]
Assume that "share private key" means share. If remaining shares can sign a correct signature, then you can use the function "[add share](https://github.com/getamis/alice/tree/add_share_readme#add-share)"  to recover losing share. 

Or in DKG, you can copy your share and store it in some safe storage.

**Comment by lyh168** [comment]
> Assume that "share private key" means share. If remaining shares can sign a correct signature, then you can use the function "[add share](https://github.com/getamis/alice/tree/add_share_readme#add-share)" to recover losing share.
> 
> Or in DKG, you can copy your share and store it in some safe storage.

thank you ,  "add share" can solve this problem
