### ISSUE TITLE
Expose v bit in the signature in addition to r,s

### ISSUE THREAD

**Issue by bharathrao** [getamis/alice#117]
FEATURE REQUEST:

Verification of signed messages requires v,r,s components of signature. Currently, a tss signature produces only r and s. The v needs to be computed separately. v can have 4 values. The encoding for v (called recid) depends on the blockchain, whether the address is compressed etc. For bitcoin uncompressed address, the value is 27 or 28 in almost all cases. From compressed addresses it would be 31,32

https://en.bitcoin.it/wiki/BIP_0137#Specification

Ideally, there is a way to generate the v part as well. Blockchain specific encoding is optional. Only values 0,1,2,3 is needed.

**Comment by markya0616** [comment]
Hello @bharathrao, please refer https://github.com/getamis/alice/pull/118 to generate the v part for ETH blockchain.

**Comment by cychuang0924** [comment]
This issue has been solved. So close it.
