### ISSUE TITLE
Support BIP32

### ISSUE THREAD

**Issue by k8docker** [getamis/alice#119]
Feature request

Possible to have 1 share key with multiple public key addresses?

According to Fast Multiparty Threshold ECDSA with Fast Trustless Setup, 
"Our key sharing is compatible with BIP32 public derivations, and we leave it as future work to prove security in this setting."

Tss-ecdsa-cli seems to have support for HD keys
https://github.com/cryptochill/tss-ecdsa-cli

**Comment by cychuang0924** [comment]
Thanks for your suggestion.

In fact, Tss-ecdsa-cli  has not support for all cases of HD keys.

Bip32 describes two methods to derive child keys. One child key is called hardened key. Another case is called non-hardened key.

Tss-ecdsa-cli only supports the non-hardened key case.

The good news is: we are able to release a new version so as to support BIP32 completely including hardened key case. So far, this feature only supports that threshold is 2. 

If you have any question, please let me know. Thanks!

**Comment by k8docker** [comment]
Thanks.. any roadmap for the new version?

**Comment by cychuang0924** [comment]
We have started merging out code. For example: https://github.com/getamis/alice/pull/120
If everything goes well, we will release it in the next month.

**Comment by cychuang0924** [comment]
@k8docker  We are happy to inform you that we have released a beta version of bip32. If you have any suggestions, welcome to let us know. Thanks!
