### ISSUE TITLE
Is any method to verify threshold signature?

### ISSUE THREAD

**Issue by Joshuacccc** [getamis/alice#149]
**I wonder how can I verify the correctness of the signature?**:

**Is there a corresponding verification method provided?**:

**Comment by cychuang0924** [comment]
Hi Joshuacccc, 

 You can use the standard verification of ECDSA. For example,
 https://github.com/getamis/alice/blob/6091f369123391a2899b34e19b40a7040f2e7c68/crypto/tss/signer/signer_test.go#L90

If you have any question, please let me know. Thanks.

**Comment by cychuang0924** [comment]
It seems be solved.
