### ISSUE TITLE
how to use ginkgo to run one test case

### ISSUE THREAD

**Issue by alexSmallWorld** [getamis/alice#172]
In alice, there a lot of test case in one package, but i just want to run only one test case, like in tss/dkg, i just want to test dkg_test.go. 
Like in go.testing, I run `go test -run NewDKG` will only run one case.

**Comment by markya0616** [comment]
You should use `Focus Apecs`.
https://goo.gl/maps/mvUg74rRUDPixsMf8

**Comment by alexSmallWorld** [comment]
it works, thanks.
