### ISSUE TITLE
KS-AMC-F-05 : Messages sent as P2P instead of broadcast

### ISSUE THREAD

**Issue by cychuang0924** [getamis/alice#197]
**Severity**: High

**Description and Impact Summary**:

At the end of the first round of the presign phase, both in the 3-round and the 6-rounds variants (Fig. 7 and 9 of the paper, respectively), there is certain data that must be sent (privately, e.g., on a secure channel) to some other peers, and some data that must be reliably broadcast to all peers.

However, in the code (sendRound1Messages) there is no such distinction, and all these messages are communicated peer-to-peer to every other party. This introduces potentially serious vulnerabilities, as there is no way to make sure that a malicious party is not sending the same “public” values to everyone else. In fact, a malicious party could “segment” the pool of other participants by sending a certain value to some of them, and another value to all the others. This is similar to the “forget-and- forgive” attack described for example in https://eprint.iacr.org/2020/1052.pdf (more information here).

**Comment by cychuang0924** [comment]
We fix it distinguishing the type of messages. One type is "broadcast" and another is "private send". For the case "broadcast", we will apply echo protocol to solve this issue according to the recommendation in the CGGMP paper.

**Comment by markya0616** [comment]
https://github.com/getamis/alice/pull/205
