### ISSUE TITLE
Proof of the Paillier public key in the hierarchical threshold signature protocol

### ISSUE THREAD

**Issue by chrustyp** [getamis/alice#209]
Hi all.

In step 1, e of the hierarchical threshold signature algorithm, the participant $\mathfrak{P}_i$ is required to send the proof of the public key $P_i$ they generated in step 1,a. Let's say we choose the public key to be generated for the Paillier cryptosystem. In step 1,e, the author has written the following:

![image](https://user-images.githubusercontent.com/115155493/194301567-7ab11ea1-ad6e-49b6-a5bf-1ed5da1478cf.png)

I am uncertain exactly what is meant by "In Paillier case, the proof is the integer factorisation of $P_i$". Would you mind clarifying this issue for me?

**Comment by cychuang0924** [comment]
Hi chrustyp,
     The private key of Paillier cypto-system can be generated by two big prime integers p and q. So this proof prove that the sender actually knows the private key associated with this public key N =pq, because he can generate a valid "factorization proof" of the public key N.
     
If you have any question, please let me know. Thanks!
