### ISSUE TITLE
Puzzlement of function CheckValid in birkhoffinterpolation.go

### ISSUE THREAD

**Issue by SFNaXiao** [getamis/alice#225]
**Is this a BUG REPORT or FEATURE REQUEST?**:
It may be a bug.
**What happened**:
The traversal of the combinations does not play a real role. For example, when a combination cannot obtain the  birkhoffMatrix or the rank of the birkhoffMatrix is not equal to the threshold, it directly returns an error without continuing to view the next combination.
 In addition, when a legal combination is found, it does not directly return nil, but continues to check the subsequent combinations, so that the final return may be an error.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by cychuang0924** [comment]
Hi, SFNaXiao,

   You are right! We will fix it. Thanks a lot again!

**Comment by cychuang0924** [comment]
Fix it in https://github.com/getamis/alice/pull/226 Thanks for your finding!

**Comment by SFNaXiao** [comment]
You're welcome.
