### ISSUE TITLE
Protobuf namespace conflict when importing both eddsa and ecdsa signer packages

### ISSUE THREAD

**Issue by zhelnov** [getamis/alice#235]
Hi,

I need both `eddsa/frost` and `ecdsa/gg18` algorithms in my go binary, but when i have both imports in same package as follows:
```
import (
  ecdsaSigner "github.com/getamis/alice/crypto/tss/ecdsa/gg18/signer"
  eddsaSigner "github.com/getamis/alice/crypto/tss/eddsa/frost/signer"
  ...
)
```
then i getting protobuf error in runtime:
```
panic: proto: file "github.com/getamis/alice/crypto/tss/ecdsa/gg18/signer/message.proto" has a name conflict over signer.Type
	previously from: "github.com/getamis/alice/crypto/tss/eddsa/frost/signer"
	currently from:  "github.com/getamis/alice/crypto/tss/ecdsa/gg18/signer"
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```
as i get from docs protobuf declarations are globally scoped across go binary named distinctly by packages name and var name. The problem is both `eddsa/frost` and `ecdsa/gg18` has same package name `signer` and pretty the same protobuf declaration collections.

Is there any chance i can solve it on my side? Otherwise would be nice to resolve such namespace conflict on library level.

**Comment by cychuang0924** [comment]
Hi @zhelnov,

   This issue has been fixed in the PR: https://github.com/getamis/alice/pull/237#pullrequestreview-1292497381 by @markya0616.

If you have any problems, please let us know. Thanks!

**Comment by zhelnov** [comment]
@cychuang0924, @markya0616 thank you very much guys for quick response and fix! Just checked it, it works flawlessly now.
