### ISSUE TITLE
Have you do range proofs in the Mta functions？

### ISSUE THREAD

**Issue by MaggieNgWu** [getamis/alice#246]
There's a range check in Mta function, but no range proof, is that right? What kind of attacks can happen if not do range proof?

**Comment by cychuang0924** [comment]
Hi MaggieNgWu,

The original algorithm of GG18 without ZK range proof is insecure. More details can be found in 

[A Note on the Security of GG18](https://info.fireblocks.com/hubfs/A_Note_on_the_Security_of_GG.pdf)

and 

[Alpha-Rays: Key Extraction Attacks on Threshold ECDSA Implementations](https://eprint.iacr.org/2021/1621)

In brief, this version of Mta has a risk of losing the private key.

Therefore, the authors of[ section 5 in GG18 ](https://eprint.iacr.org/2019/114.pdf)revised their algorithm. 

They claimed that replace sMtA the MtA and MtAwc protocols and some other assumptions, then their protocol is safe (ref. Theorem 2).

In our implementation of GG18, we implement this version of GG18 (i.e. sMta).

If you still have some concerned of this Mta without range proof, then you can use CGGMP. In this version, our 

implementations includes all range proofs. If you have any questions, please let me know. Thank you!

**Comment by MaggieNgWu** [comment]
Do you mean that:

1. Your GG18 implementation is using sMta, that is safe.
2. The CGGMP includes all range proofs.

Is that right?

**Comment by MaggieNgWu** [comment]
Does sMta safe enough to prevent information leak?

**Comment by cychuang0924** [comment]
> Do you mean that:
> 
> 1. Your GG18 implementation is using sMta, that is safe.
> 2. The CGGMP includes all range proofs.
> 
> Is that right?

Right!

The performance of CGGMP is faster except for Reshare protocol. Because reshare protocol in CGGMP will renew Paillier private key, which is a product of two safe primes.
