### ISSUE TITLE
The map relation in https://github.com/getamis/alice/tree/master/crypto/homo/cl

### ISSUE THREAD

**Issue by XinwenXiang** [getamis/alice#248]
**Is  a  FEATURE REQUEST?**:

**I want to use the map relation in CL**:

**Reading the paper **:
![image](https://user-images.githubusercontent.com/33709586/230025057-df7a1133-8cb1-4f0a-8615-4cc4d524c4c8.png)

By referencing your repository code in https://github.com/getamis/alice/tree/master/crypto/homo/cl, I want to follow yout construction to build an CL encryption, in my implementation, i need a map relation like **CL15 C(OΔp^2) to C (OΔk)**, but in your repo i do not find its implementation.

How can I achieve my goal?

**Comment by cychuang0924** [comment]
Hi XinwenXiang,

We do not implement this part. If we have time, we will help you! There is a paper which maybe help you.

https://link.springer.com/chapter/10.1007/978-3-030-16458-4_20

**Comment by XinwenXiang** [comment]
thanks for your answer, i found https://gite.lirmm.fr/crypto/bicycl. 
It seems that this library has implemented this part. I will read the paper later ：）
