### ISSUE TITLE
Question) Instructions to use the BIP32 child index

### ISSUE THREAD

**Issue by Hoodie-Kang** [getamis/alice#249]
Hi,

I used the childIndex, which is defined in the child_test.go as "2147483648" , and I found that the index determines the pubkey, share and some other info.
So I can figure out the meaning of the child index but can't find the instruction to use it, such as length, conditions, or something.

I would appreciate you to help me to know the instruction, references, or some examples!
Thanks

**Comment by cychuang0924** [comment]
Hi Hoodie-Kang,

The meaning of the child index is defined in the [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)

**Comment by Hoodie-Kang** [comment]
Awesome, Thanks!
