### ISSUE TITLE
If I want to support currencies such as neo and ont, ecdsa-p256. Can Alice be satisfied?Issue brief description

### ISSUE THREAD

**Issue by CodeLion66** [getamis/alice#250]
If I want to support currencies such as neo and ont, ecdsa-p256. Can Alice be satisfied?

![image](https://user-images.githubusercontent.com/20180897/234198655-5c4de380-d1e8-448f-9863-3e8b9d6d9b47.png)

**Comment by cychuang0924** [comment]
Repeated issue https://github.com/getamis/alice/issues/252
