### ISSUE TITLE
signature verification in evm(solidity)

### ISSUE THREAD

**Issue by Dmytro-yakymuk** [getamis/alice#253]
maybe there are some cases of using signatures from your examples in evm contracts?
what are the verification options? i just know ECDSA.recover(hash, signature)
from @openzeppelin/contracts/utils/cryptography/ECDSA.sol

where there is v value
```
if (signature.length == 65) {
            bytes32 r;
            bytes32 s;
            uint8 v;
            // ecrecover takes the signature parameters, and the only way to get them
            // currently is to use assembly.
            /// @solidity memory-safe-assembly
            assembly {
                r := mload(add(signature, 0x20))
                s := mload(add(signature, 0x40))
                v := byte(0, mload(add(signature, 0x60)))
            }
            return tryRecover(hash, v, r, s);
    } else {
    return (address(0), RecoverError.InvalidSignatureLength);
}
```

**Comment by cychuang0924** [comment]
This PR maybe help you https://github.com/getamis/alice/pull/118

If you have any question, please let me know.

Thanks a lot!

**Comment by Dmytro-yakymuk** [comment]
It helped, thanks!

**Comment by Dmytro-yakymuk** [comment]
> Hi Dmytro-yakymuk, This PR maybe help you #118
> 
> If you have any question, please let me know.
> 
> Thanks a lot!

It helped, thanks!
