### ISSUE TITLE
Does tss support schnorr signatures?

### ISSUE THREAD

**Issue by york0xiong** [getamis/alice#279]
The  taproot address of btc need use schnorr to sign, Does this support schnorr signatures?

**Comment by cychuang0924** [comment]
Hi york0xiong,
  This library has supported Schnorr signature (i.e. FROST):  https://github.com/getamis/alice/blob/master/crypto/tss/eddsa/frost/README.md

**Comment by york0xiong** [comment]
Thanks for your reply. alice's eddsa uses ed25519 curve and schnorr signature, but Btc's taproot uses secp256k1 and schnorr signature. Can alice support it

**Comment by cychuang0924** [comment]
Hi [york0xiong](https://github.com/york0xiong),
    Is what the following file describes is what you want? 
    https://github.com/bitcoin/bips/blob/master/bip-0340.mediawiki
    
    Can I do this based on the following [code](https://github.com/bitcoin/bips/blob/master/bip-0340/reference.py)？

Thanks your explain!

**Comment by cychuang0924** [comment]
Hi york0xiong,
We have support Schnorr signature given in BIP340: Taproot.
If you have any question, please let us know.

Here : https://github.com/getamis/alice/pull/284
