### ISSUE TITLE
Should one use v1.0.2 or master? v1.0.2 cannot use refreshed shares

### ISSUE THREAD

**Issue by randomshinichi** [getamis/alice#282]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Question
**What happened**:
ALICE v1.0.2 does not export `refresh.Result`'s fields. This is an oversight, which the `master` branch fixes. But it is unclear how production-ready master branch is.
Without `refresh.Results`'s fields being exported, how can one use the refreshed shares to sign something?

**Comment by markya0616** [comment]
https://github.com/getamis/alice/releases/tag/v1.0.3
We just published a new version, v1.0.3.
