### ISSUE TITLE
Add a new node in example

### ISSUE THREAD

**Issue by B08902060** [getamis/alice#287]
I want to add a new node_i in example ,but I don't know how to set up the "identity","id" in `node-i.yaml`

**Comment by alanchchen** [comment]
@B08902060 The `identity` represents the `peer key`. (Sorry for the confusing naming) 
It's a random generated private key and the `id` is the derived peer identity.
See https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md for more information.
And https://github.com/getamis/alice/blob/master/example/cggmp/dkg/main.go#L78 for how the example uses them.

Just generate bytes randomly (with the same length) by yourself.
