### ISSUE TITLE
KS-AMIS-F-01: Hash of Multiple Parameters Without Domain Separation

### ISSUE THREAD

**Issue by cychuang0924** [getamis/alice#44]
Severity: Medium

**What happened**:
In hash.go the function getDigest computes the (keyed) hash function Blake2 of a byte
array originData using another byte array salt as cryptographic salt.

L114 checkData := append(originData, salt...)
L115 digest := blake2b256.Sum(checkData)

However, there is no check on the size of salt and no domain separation between
salt and data. This would allow to call the function maliciously and generate collisions,
because, e.g., the hash of (foo , bar) and (fo , obar) would be the same.

**Comment by markya0616** [comment]
We convert salt and data bytes into a proto message, and calculate its hash.
https://github.com/getamis/alice/pull/74/files#diff-dfdc0651fd0a89d5c96d2a275b3ed353R210
