### ISSUE TITLE
Question about resharing

### ISSUE THREAD

**Issue by LorenzoAlluminio** [getamis/alice#91]
Hello!
I'm still trying to use the library and playing a bit with the /example code.

I'd like to ask you this, when doing a resharing how can I increment/decrement the number of shares?
Moreover, when resharing is it possible to modify the threshold? if yes, how?

Thanks and sorry for the inconvenience

**Comment by bun919tw** [comment]
Hi @LorenzoAlluminio ,

Thanks for asking.

### Adjust the number of shares?

A: Partial yes.

The scenario in the example is a 3-of-3 TSS. Therefore, all parties involved in DKG must participate in resharing. However, in reshare, we only stipulate the number of participants should not be less than threshold.

**So, it's relatively easy to decrease the number of shares.**

To perform a decrement, you first need to modify the example to a 2-of-3 TSS by changing the `threshold` to 2 in DKG configs (also in reshare configs). Then, you can have only two parties to do a resharing. In this way, you decrease the number of shares from 3 to 2 and change the example to a 2-of-2 TSS.

On the other hands, theoretically, you could also increase the number of shares. However we don't provide `AddShares()` in alice. We think this function is not so practical. If you want to adjust the formation or the hierarchy of an account, we think a better way to do this is to start over by performing DKG again and transferring the funds to the new account.

### Adjust threshold?

A: Partial yes.

You could increment the threshold when doing a resharing. To do this experiment, you also need to modify the example to a 2-of-3 TSS first (change the `threshold` to 2 in DKG configs). After resharing, you change the example back to 3-of-3 TSS. In the nutshell, resharing is to add a new polynomial to the old one. With larger threshold when doing a resharing, you add a new polynomial with higher degree.

However, on the contrary, if you add a new polynomial with lower degree, the degree of the result polynomial will never be lower than the original one (you couldn't eliminate the highest degree term). Therefore, it's impossible and unrecommended (not safe) to decrease the threshold when doing a resharing.

However, there's a chance we accidentally decrease the threshold when doing a normal resharing. We might add a same degree polynomial whose highest degree term could eliminate the one in the original polynomial. Then the resulting threshold will be smaller than before. Still, the possibility is very very low.

**Comment by LorenzoAlluminio** [comment]
Thanks for the detailed reply!!
Me and some other students are trying to use your library to implement a sort of distributed certificate authority for a school project, so our setting is a bit different from the one the library is made to address I guess.
The idea is that the CA of each organization has a share and at minimum a majority of the CAs has to agree to sign when generating a certificate.
That's why we were wondering if it was possible to add shares and modify the threshold while maintaining the same public key. This is needed because otherwise the certificates would become invalid.

Anyway yes, I gave it a star since it's the only library on TSS that is well done and well documented right now :)

**Comment by bun919tw** [comment]
Thanks for the compliment.

Yes, your scenario sounds reasonable to use `AddShare()` function. We might add this functionality in the future but the schedule is unsure yet. In the meantime, It's still a viable alternative to do resharing to achieve adding shares in your scenario.

To be noted, in a t-of-n TSS, it still requires at least `t` participants to add a new share. Nevertheless, compared with resharing which requires all `n` participants, it cost less.

**Comment by zhangtianai** [comment]
Has this AddShare() method been added?  It's useful

**Comment by bun919tw** [comment]
Not yet.
We will do this feature in July.

**Comment by zhangtianai** [comment]
Thanks
I'm looking forward to this feature

**Comment by zhangtianai** [comment]
when doing a resharing how can I increment/decrement the number of shares? Is it modified here? How to change it? Can you give me some advice


func (p *verifyHandler) Finalize(logger log.Logger) (types.Handler, error) {
	var err error

	// Build the new share, the sum of f^(n_j)(x_j) plus the original share
	poly := p.poly.Differentiate(p.bk.GetRank())
	p.newShare = new(big.Int).Add(p.oldShare, poly.Evaluate(p.bk.GetX()))
	for _, peer := range p.peers {
		v := getMessageByType(peer, Type_Verify).GetVerify().GetVerify()
		p.newShare = new(big.Int).Add(p.newShare, new(big.Int).SetBytes(v.Evaluation))
	}
	p.newShare = new(big.Int).Mod(p.newShare, p.publicKey.GetCurve().Params().N)

	// Build and send out the result message
	p.siGProofMsg, err = zkproof.NewBaseSchorrMessage(p.publicKey.GetCurve(), p.newShare)
	if err != nil {
		log.Warn("Failed to new si schorr proof", "err", err)
		return nil, err
	}

	msg := p.getResultMessage()
	p.broadcast(msg)
	return newResultHandler(p), nil
}


Urgently needed

**Comment by bun919tw** [comment]
You don't need to modify the library. You could achieve it by only modifying the config in `/example`.

1. Re-configure the example to a 2-of-3 TSS

In file `example/dkg/id-10001-input.yaml`:

```yaml
port: 10001
rank: 0
threshold: 2
peers:
  - 10002
  - 10003
```

And you should also change the threshold in other two config files.

2. Run DKG process
3. Configure resahre

In file `example/reshare/id-10001-input.yaml`:

```yaml
port: 10001
threshold: 2
peers:
  - 10002
share:
  (copy from dkg output)
pubkey:
  (copy from dkg output)
bks:
  id-10001:
    (copy from dkg output)
  id-10002:
    (copy from dkg output)
```

In file `example/reshare/id-10002-input.yaml`:

```yaml
port: 10002
threshold: 2
peers:
  - 10001
share:
  (copy from dkg output)
pubkey:
  (copy from dkg output)
bks:
  id-10001:
    (copy from dkg output)
  id-10002:
    (copy from dkg output)
```

In this way, you kick out the participant whose id is `id-10003`. You decrement the number of shares to 2 and the example become a 2-of-2 TSS.

**Comment by zhangtianai** [comment]
The effect we want is that when the number of shares changes,But the public key cannot change

**Comment by bun919tw** [comment]
The decrement should not change the public key.

After the process, I use the new shares of `id-10001` and `id-10002` and the same public key (generated from DKG) to sign. It works as expected.

How do you know the public key changed? Resharing will only output the new share, not a new public key.

**Comment by zhangtianai** [comment]
step 1 change example/dkg/id-10001-input.yaml
port: 10001
rank: 0
threshold: 2
peers:
  - 10002
step 2 example/dkg/id-10002-input.yaml
port: 10002
rank: 0
threshold: 2
peers:
  - 10001

result:
share: "57027150604480329025656736059239198072102019215124488942367244347836785179811"
pubkey:
  x: "47182665548776258155602680717417073059896494913460575217002937635715515897874"
  "y": "9845347197541856154712814128848414136874512245383562642049906907326757007581"
bks:
  id-10001:
    x: "16331944809270083120596802726489904524838243975966093878325787056562877773185"
    rank: 0
  id-10002:
    x: "3595868606727736170784437639525360079568026941041608070074852627418326587929"
    rank: 0

the old result is:
share: "366743784979485201291255755834160846443767639384864346370202452776464727086"
pubkey:
  x: "19447374317316832984300699552693378039221004648710431534967789915065950757110"
  "y": "107846179478921329230746134722746276825392630991278129381825866968670387585625"
bks:
  id-10001:
    x: "89701399581614591286031197476086126846779207318311991286744006464029159762811"
    rank: 0
  id-10002:
    x: "14867536297762217692303999989525093472679020132874134102537683316675546995285"
    rank: 0
  id-10003:
    x: "111073014081370055487450981697930810808667556432426373731417254865209908194966"
    rank: 0

the pubkey is changed

**Comment by bun919tw** [comment]
I don't know what's the configuration of this old result. Is it a 3-of-3 TSS or a 2-of-3 TSS?

Also, you are still doing wrong. You should change `example/dkg/id-10003-input.yaml` file. `id-10003` should be involved when DKG. You need to setup a 2-of-3 TSS first (3 parties with threshold 2). Then, you could decrease the number of shares to 2 by resharing the scheme to a 2-of-2 TSS.

**Comment by zhangtianai** [comment]
Thanks a million！
Okay, I do it your way. The result is ok，decrement the number of shares  successfully.

**Comment by zhangtianai** [comment]
**DKG**

On node A,
> ./example dkg --config dkg/id-10001-input.yaml

On node B,
> ./example dkg --config dkg/id-10002-input.yaml

On node C,
> ./example dkg --config dkg/id-10003-input.yaml

After DKG, there are 3 new output files created in example/dkg folder. and there is a share in each folder，temporary naming shareA，shareB and shareC

**Reshare**

On node A,
> ./example reshare --config reshare/id-10001-input.yaml

On node B,
> ./example reshare --config reshare/id-10002-input.yaml

On node C,
> ./example reshare --config reshare/id-10003-input.yaml

After reshare, there are 3 new output files created in example/reshare folder and there a new share in each folder, temporary naming sharenewA，sharenewB and sharenewC

**Question**
After reshare, Only new share can be signed and the old share should be invalid. But I still can use shareA，shareB and shareC to singer, why?

**Comment by bun919tw** [comment]
The old shares and the new shares will correspond to the same public key so both sets of the shares could sign successfully. The idea of resharing (refresh share) is to "rotate the shares". Ideally, you need to delete the old share right after resharing. If every party follows this measure, it will reduce the possibility of funds being stolen.

Let's imagine a scenario. A hacker somehow hacked one share in a 2-of-3 TSS, but they constantly refreshing their shares. If they deleted old shares after resharing, the old share that hacker stole will become useless. The hacker will need to steal at least two new shares to move the funds since the old share could not sign correctly combined with the new share.

> proactive secret sharing can be used to periodically reshare a secret, thereby periodically reducing to zero the number of compromised shares. However, an abstract security model is not enough to assess the effects of placing a threshold scheme in an adversarial environment. One also needs to characterize implementation aspects whose variation may affect security. These include the types of threshold, the communication interfaces, the target computing platforms, and the setup and maintenance requirements.

The above quote is from [NIST document](https://nvlpubs.nist.gov/nistpubs/ir/2019/NIST.IR.8214.pdf).

**Comment by zhangtianai** [comment]
Thanks for the detailed reply!!

**Comment by zhangtianai** [comment]
I'm sorry to bother you again，I know you will do this feature in July. 
At present, I need the `Addshare` function urgently.so I tried to add a method

```
func TestAddshare(t *testing.T) {
	config := &ReshareConfig{}
	yamlFile, err := ioutil.ReadFile("/Users/alice/go/src/alice/example/signer/id-10001-input.yaml")
	if err != nil {
		fmt.Println("err:", err)
	}
	err = yaml.Unmarshal(yamlFile, config)
	if err != nil {
		fmt.Println("err:", err)
	}
	fmt.Println("c:", config)
	dkgResult, err := utils.ConvertDKGResult(config.Pubkey, config.Share, config.BKs)
	publicKey := dkgResult.PublicKey

	curve := publicKey.GetCurve()
	fieldOrder := curve.Params().N
	// Random x and build bk
	x, _ := utt.RandomPositiveInt(fieldOrder)
	// host, err := peer.MakeBasicHost(config.Port)
	if err != nil {
		log.Crit("Failed to create a basic host", "err", err)
	}
	fmt.Println("addnewshare id-x:", x)
}

```

then output：
`addnewshare id-x: 58904964964173434700102933026460316542053656842356209512915405655856347352898`

But I can use it to signer successful.Is this the right way？

**Comment by cychuang0924** [comment]
You only generate x, so I regard this method which can not work. A correct share needs: rank, x, y.
The difficult part of add share is generating a correct "y" such that the new share can work. For generating a correct "y",  it needs at least t shares involving.

More discussion can be found in [paper](https://link.springer.com/chapter/10.1007/978-3-319-49175-2_2).

**Comment by cychuang0924** [comment]
Roughly speaking, the private key and the corresponding public key have been determined by a polynomial after DKG. Therefore, if you want to add a correct share, you have to recover this polynomial. However, in your code, you generate a new polynomial, which are different, so the share does not work.

**Comment by zhangtianai** [comment]
yeah, you are right.I try two ways to solve this problem
Solution 1
`modify the DKG method`
Solution 2
`modify the reshare method`
In Solution 1, The difficulty is do not know its exact form of polynomial
In Solution 2,`reshare, err := NewReshare(pm, config.Threshold, dkgResult.PublicKey, dkgResult.Share, dkgResult.Bks, s)`,the old share is nil for new.
I don't know what to do.Do you know any other way to deal with it？

**Comment by zhangtianai** [comment]
I make the fixed exact form of polynomial, still signer error

```
func TestAddshare(t *testing.T) {
	config := &ReshareConfig{}
	yamlFile, err := ioutil.ReadFile("/Users/alice/go/src/alice/example/signer/id-10001-input.yaml")
	if err != nil {
		fmt.Println("err:", err)
	}
	err = yaml.Unmarshal(yamlFile, config)
	if err != nil {
		fmt.Println("err:", err)
	}
	fmt.Println("config data:", config)
	dkgResult, err := utils.ConvertDKGResult(config.Pubkey, config.Share, config.BKs)
	publicKey := dkgResult.PublicKey

	if publicKey.IsIdentity() {
		fmt.Println("publicKey IsIdentity")
	}

	curve := publicKey.GetCurve()
	fieldOrder := curve.Params().N

	coefficients := []*big.Int{big.NewInt(1), big.NewInt(5), big.NewInt(2), big.NewInt(3)}
	poly, err := polynomial.NewPolynomial(fieldOrder, coefficients)

	for i := 1; i <= 4; i++ {
		x, _ := utt.RandomPositiveInt(fieldOrder)
		fmt.Println("addnewshare id-x:", x)
		tempPoly := poly.Differentiate(uint32(0))
		newShare := tempPoly.Evaluate(x)
		newShare = new(big.Int).Mod(newShare, fieldOrder)
		fmt.Println("newshare:", newShare)
	}

}
```

**Comment by cychuang0924** [comment]
This [paper](https://link.springer.com/chapter/10.1007/978-3-319-49175-2_2) offers an algorithm of  AddShare()(PS. called Add). Alice has enough methods to help you implement it.

The working flow of AddShare is like:
1. Get t old shares together.
2. Use Birkhoff interpolation (i.e. in your case, that is Lagrange interpolation) to get
    the original polynomial f(x).
3 Generate a new rank =0, an x_new coordinate, then the corresponding new share is y_new := f(x_new).

At last, you can get the new share (0, x_new, y_new).

The above flow is the core of idea of AddShare(). However, for avoiding to recover the polynomial f(x)(i.e. because it includes the secret key f(0)), authors in the paper use MPC to attain the new share. The latter method is safer.

**Comment by zhangtianai** [comment]
Thanks for the detailed reply!!
The way of MPC to attain the new share is perfect solution.Can you show me a demo?

**Comment by zhangtianai** [comment]
Is the right method `ComputeBkCoefficient` to get
the original polynomial？

**Comment by zhangtianai** [comment]
```poly := p.poly.Differentiate(p.bk.GetRank())
p.newShare = new(big.Int).Add(p.oldShare, poly.Evaluate(p.bk.GetX()))
for _, peer := range p.peers {
	v := getMessageByType(peer, Type_Verify).GetVerify().GetVerify()
	p.newShare = new(big.Int).Add(p.newShare, new(big.Int).SetBytes(v.Evaluation))
}
p.newShare = new(big.Int).Mod(p.newShare, p.publicKey.GetCurve().Params().N)
```

In  reshareing, Why need to add the p.oldShare？

**Comment by cychuang0924** [comment]
Unfortunately, we do not have any demo now. The function ComputeBkCoefficient only gives the constant of the original polynomial.
In TSS, all participants determine a polynomial such that the constant term is their determined private key.

In reshare, each participant chooses a new polynomial with the zero constant such that and adding it to the original polynomial such that the two constant terms are the same. Reformulating this active by share language  is that "adding old share"(i.e. corresponding to the original polynomial ) to "new translate"(i.e. "the chosen a new polynomial"). 






In the progress of share, each participant chooses a new translate adding to the original share such that the const
