### ISSUE TITLE
Will the addshare feature be released in July?

### ISSUE THREAD

**Issue by zhangtianai** [getamis/alice#95]
Will the addshare feature be released in July?

**Comment by cychuang0924** [comment]
According to our plan, we will do it in July.

**Comment by cychuang0924** [comment]
@ LorenzoAlluminio @zhangtianai We release "Add share". If you still have interest, you can check it. So far, we have not updated readme and added "add share" in example.

**Comment by cychuang0924** [comment]
@LorenzoAlluminio @zhangtianai We release "Add share". If you still have interest, you can check it. So far, we have not updated readme and added "add share" in example. If you have any suggestions, you can connect us directly without any hesitation.
